require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe VehicleConsumptionsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # VehicleConsumption. As you add validations to VehicleConsumption, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VehicleConsumptionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all vehicle_consumptions as @vehicle_consumptions" do
      vehicle_consumption = VehicleConsumption.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:vehicle_consumptions)).to eq([vehicle_consumption])
    end
  end

  describe "GET #show" do
    it "assigns the requested vehicle_consumption as @vehicle_consumption" do
      vehicle_consumption = VehicleConsumption.create! valid_attributes
      get :show, {:id => vehicle_consumption.to_param}, valid_session
      expect(assigns(:vehicle_consumption)).to eq(vehicle_consumption)
    end
  end

  describe "GET #new" do
    it "assigns a new vehicle_consumption as @vehicle_consumption" do
      get :new, {}, valid_session
      expect(assigns(:vehicle_consumption)).to be_a_new(VehicleConsumption)
    end
  end

  describe "GET #edit" do
    it "assigns the requested vehicle_consumption as @vehicle_consumption" do
      vehicle_consumption = VehicleConsumption.create! valid_attributes
      get :edit, {:id => vehicle_consumption.to_param}, valid_session
      expect(assigns(:vehicle_consumption)).to eq(vehicle_consumption)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new VehicleConsumption" do
        expect {
          post :create, {:vehicle_consumption => valid_attributes}, valid_session
        }.to change(VehicleConsumption, :count).by(1)
      end

      it "assigns a newly created vehicle_consumption as @vehicle_consumption" do
        post :create, {:vehicle_consumption => valid_attributes}, valid_session
        expect(assigns(:vehicle_consumption)).to be_a(VehicleConsumption)
        expect(assigns(:vehicle_consumption)).to be_persisted
      end

      it "redirects to the created vehicle_consumption" do
        post :create, {:vehicle_consumption => valid_attributes}, valid_session
        expect(response).to redirect_to(VehicleConsumption.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved vehicle_consumption as @vehicle_consumption" do
        post :create, {:vehicle_consumption => invalid_attributes}, valid_session
        expect(assigns(:vehicle_consumption)).to be_a_new(VehicleConsumption)
      end

      it "re-renders the 'new' template" do
        post :create, {:vehicle_consumption => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested vehicle_consumption" do
        vehicle_consumption = VehicleConsumption.create! valid_attributes
        put :update, {:id => vehicle_consumption.to_param, :vehicle_consumption => new_attributes}, valid_session
        vehicle_consumption.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested vehicle_consumption as @vehicle_consumption" do
        vehicle_consumption = VehicleConsumption.create! valid_attributes
        put :update, {:id => vehicle_consumption.to_param, :vehicle_consumption => valid_attributes}, valid_session
        expect(assigns(:vehicle_consumption)).to eq(vehicle_consumption)
      end

      it "redirects to the vehicle_consumption" do
        vehicle_consumption = VehicleConsumption.create! valid_attributes
        put :update, {:id => vehicle_consumption.to_param, :vehicle_consumption => valid_attributes}, valid_session
        expect(response).to redirect_to(vehicle_consumption)
      end
    end

    context "with invalid params" do
      it "assigns the vehicle_consumption as @vehicle_consumption" do
        vehicle_consumption = VehicleConsumption.create! valid_attributes
        put :update, {:id => vehicle_consumption.to_param, :vehicle_consumption => invalid_attributes}, valid_session
        expect(assigns(:vehicle_consumption)).to eq(vehicle_consumption)
      end

      it "re-renders the 'edit' template" do
        vehicle_consumption = VehicleConsumption.create! valid_attributes
        put :update, {:id => vehicle_consumption.to_param, :vehicle_consumption => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested vehicle_consumption" do
      vehicle_consumption = VehicleConsumption.create! valid_attributes
      expect {
        delete :destroy, {:id => vehicle_consumption.to_param}, valid_session
      }.to change(VehicleConsumption, :count).by(-1)
    end

    it "redirects to the vehicle_consumptions list" do
      vehicle_consumption = VehicleConsumption.create! valid_attributes
      delete :destroy, {:id => vehicle_consumption.to_param}, valid_session
      expect(response).to redirect_to(vehicle_consumptions_url)
    end
  end

end
